swagger: '2.0'
info:
  description:  NEARBY API
  version: '1.0.0'
  title: 'SWAGGER API'
schemes:
  - 'https'
  - 'http'
paths:
  /amenities:
    get:
        tags:
        - 'root'
        summary: 'Get the amenities'
        description: 'to get the amenities from the json'
        operationId: 'getAmenities'
        produces:
        - 'application/json'
        responses:
         200:
          description: 'success'    
  /toilet:
    post:
      tags:
        - 'root'
      summary: 'Add new toilet'
      description: 'Add new toilet into exiting types of toilet'
      operationId: 'addToilet'
      parameters:
        - name: toilet
          in: body
          schema:
           $ref: '#/definitions/toilet'
      produces:
        - 'application/json'
      responses:
        200:
          description: 'success'  
    delete:
      tags:
      - 'root'
      summary: 'Delete toilet'
      operationId: 'deleteToilet'
      parameters:
      - name: 'loo'
        in: 'path'
        type: 'string'
        description: "Name of the toilet that needs to be deleted"
      produces:
        - 'application/json'
      responses:
        200:
          description: 'success'
definitions:
 toilet:
  type: object
  properties:
      extraInfo:
        type: "string"
      location:
        type: "string"
      title:
        type: "string"

      
      